### ISSUE TITLE
Enemy unit tiles should not be walkable

### ISSUE THREAD

**Issue by Promtastic** [tihawk/project-hiros#17]
Due to enemy unit tiles being walkable, units are able to teleport beyond their range by attacking an enemy unit sitting in one of the furthermost tiles inside the walkable range from outside the range.

**Comment by tihawk** [comment]
This is related to the check for for attack-ability of the tile, not the walk-ability. It showcases the weakness of the tile check logic. Probably calls for some more major rewrite of the action controller logic. [code reference](https://github.com/tihawk/project-hiros/blob/master/server/battlefieldBoard/ActionController.js#L179-L208)
